#!/usr/bin/env python3
"""Install SHA256-pinned validation tools in this checkout, without global changes."""
import hashlib
import io
import json
import os
from pathlib import Path
import platform
import shlex
import subprocess
import tarfile


ROOT = Path(__file__).resolve().parent.parent
DEST = ROOT / ".tools"
LOCK = json.loads((ROOT / "scripts/bootstrap-tools.lock.json").read_text())
system = platform.system().lower()
arch = {"x86_64": "amd64", "aarch64": "arm64"}.get(platform.machine(), platform.machine())
platform_key = f"{system}-{arch}"
if platform_key not in LOCK["platforms"]:
    raise SystemExit(f"Unsupported platform: {platform_key}; supported: {', '.join(LOCK['platforms'])}")

for directory in [DEST / "bin", DEST / "downloads", DEST / "plugins/unittest", DEST / "ct/etc"]:
    directory.mkdir(parents=True, exist_ok=True)

for tool in LOCK["platforms"][platform_key]:
    name = tool["name"]
    archive = DEST / "downloads" / tool["url"].rsplit("/", 1)[-1]
    if not archive.is_file() or hashlib.sha256(archive.read_bytes()).hexdigest() != tool["sha256"]:
        print(f"Downloading {name} {LOCK['versions'][name]}", flush=True)
        subprocess.run(["curl", "--fail", "--silent", "--show-error", "--location", "--retry", "3",
                        "--proto", "=https", "--tlsv1.2", tool["url"], "--output", str(archive)], check=True)
    data = archive.read_bytes()
    if hashlib.sha256(data).hexdigest() != tool["sha256"]:
        raise SystemExit(f"SHA256 mismatch for {archive.name}")
    if tool["member"] == "":
        binary = DEST / "bin" / name
        binary.write_bytes(data)
        binary.chmod(0o755)
        continue
    with tarfile.open(fileobj=io.BytesIO(data), mode="r:gz") as tar:
        if name == "unittest":
            selected = [m for m in tar.getmembers() if m.isfile() and
                        (m.name in ["plugin.yaml", "README.md", "LICENSE"] or m.name.startswith("untt-"))]
            for member in selected:
                target = DEST / "plugins/unittest" / Path(member.name).name
                target.write_bytes(tar.extractfile(member).read())
                target.chmod(0o755 if member.name.startswith("untt-") else 0o644)
        else:
            binary = DEST / "bin" / name
            binary.write_bytes(tar.extractfile(tool["member"]).read())
            binary.chmod(0o755)
        if name == "ct":
            for member in ["etc/chart_schema.yaml", "etc/lintconf.yaml"]:
                (DEST / "ct" / member).write_bytes(tar.extractfile(member).read())

venv = DEST / "venv"
if not (venv / "bin/python3").is_file():
    subprocess.run([os.environ.get("PYTHON", "python3"), "-m", "venv", str(venv)], check=True)
subprocess.run([str(venv / "bin/python3"), "-m", "pip", "install", "--disable-pip-version-check",
                "--requirement", str(ROOT / "requirements-dev.txt")], check=True)

# The default is Helm 4. Each matrix run gets a distinct `helm` shim for ct.
for major in ["3", "4"]:
    shim = DEST / f"helm{major}-bin"
    shim.mkdir(exist_ok=True)
    link = shim / "helm"
    if link.is_symlink():
        link.unlink()
    link.symlink_to(DEST / "bin" / f"helm{major}")

quote = shlex.quote
(DEST / "env.sh").write_text(
    "# Generated by scripts/bootstrap-tools.py; source from bash or zsh.\n"
    f"export PATH={quote(str(DEST / 'helm4-bin'))}:{quote(str(venv / 'bin'))}:"
    f"{quote(str(DEST / 'bin'))}:\"$PATH\"\n"
    f"export HELM_PLUGINS={quote(str(DEST / 'plugins'))}\n"
    f"export HELM_CACHE_HOME={quote(str(DEST / 'helm-cache'))}\n"
    f"export HELM_CONFIG_HOME={quote(str(DEST / 'helm-config'))}\n"
    f"export HELM_DATA_HOME={quote(str(DEST / 'helm-data'))}\n"
)
print("Tools ready. Run: source .tools/env.sh")
